(defun timor/user-config ()
  (spacemacs/declare-prefix "o" "custom")
  (spacemacs/declare-prefix "ok" "keyboard layout")
  (spacemacs/set-leader-keys "okd" (lambda ()
				     (interactive)
				     (start-process-shell-command "xkb" nil "setxkbmap de")
				     (message "switched to de layout")))
  (spacemacs/set-leader-keys "oku" (lambda ()
				     (interactive)
				     (start-process-shell-command "xkb" nil "setxkbmap us")
				     (message "switched to us layout")))
  (spacemacs/set-leader-keys "br" 'rename-buffer))
